In [14]:
import pandas as pd
from sklearn.datasets import load_iris
import numpy as np

In [2]:
iris=load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:150]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                 4.6               3.2                1.4               0.2   
48                 5.3               3.7                1.5               0.2   
49                 5.0               3.3                1.4               0.2   
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

         flower  
47       setosa  
48       setosa  
49       setosa  
50   versicolor  
51   versicolor  
..          ...  
145   virginica  
146   virginica  
147   virginica  
148   virginica  
149   virginica  

[103 rows x 5 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [9]:
from sklearn.svm import SVC
model=SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [10]:
model.score(X_test, y_test)

1.0

In [11]:
from sklearn.model_selection import cross_val_score

In [12]:
score1=cross_val_score(SVC(kernel='rbf',C=30,gamma='auto'),iris.data,iris.target)
score1

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [15]:
np.average(score1)

0.96

In [16]:
cross_val_score(SVC(kernel='linear',C=20,gamma='auto'),iris.data,iris.target)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [17]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [19]:
from sklearn.model_selection import GridSearchCV

In [22]:
clf=GridSearchCV(SVC(gamma='auto'), {
   'C':[1,10,20],
   'kernel':['rbf','linear'],
}, cv=5, return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00197411, 0.0012136 , 0.00199332, 0.00249252, 0.00138111,
        0.00067468]),
 'std_fit_time': array([0.00057239, 0.00092406, 0.00135097, 0.00037197, 0.00117172,
        0.00060561]),
 'mean_score_time': array([0.00106573, 0.00188346, 0.00186973, 0.00098143, 0.00089788,
        0.0017025 ]),
 'std_score_time': array([0.0006681 , 0.00144006, 0.00104412, 0.00057278, 0.00125192,
        0.0021953 ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [23]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001974      0.000572         0.001066        0.000668       1   
1       0.001214      0.000924         0.001883        0.001440       1   
2       0.001993      0.001351         0.001870        0.001044      10   
3       0.002493      0.000372         0.000981        0.000573      10   
4       0.001381      0.001172         0.000898        0.001252      20   
5       0.000675      0.000606         0.001702        0.002195      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [24]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [25]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run

In [27]:
clf.best_score_

0.9800000000000001

In [28]:
clf.best_estimator_

SVC(C=1, gamma='auto')

In [30]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [40]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(SVC(gamma='auto'), {
   'C':[1,10,20],
   'kernel':['rbf','linear'],
}, cv=5, n_iter=2, return_train_score=False)
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [41]:
df1=pd.DataFrame(rs.cv_results_)
df1

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.001471      0.000827         0.001209        0.001403          rbf   
1       0.003311      0.002791         0.000286        0.000572       linear   

  param_C                         params  split0_test_score  \
0      20     {'kernel': 'rbf', 'C': 20}           0.966667   
1      20  {'kernel': 'linear', 'C': 20}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0                0.9           0.966667                1.0   
1                1.0                0.9           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.966667        0.036515                1  
1         0.966667        0.042164                2

In [42]:
df1[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1      20       linear         0.966667