In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.datasets import load_iris

In [6]:
iris=load_iris()

In [7]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [60]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [52]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [53]:
iris.target[0:150]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2)

In [33]:
clas=linear_model.LogisticRegression()
clas.fit(x_train,y_train)

LogisticRegression()

In [34]:
clas.predict(x_test)

array([1, 2, 1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2,
       2, 1, 0, 0, 1, 1, 2, 2])

In [35]:
y_test

array([1, 2, 1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2,
       2, 1, 0, 0, 1, 1, 2, 2])

In [36]:
clas.score(x_test,y_test)

0.9333333333333333

In [37]:
sample1 = [[5.1, 3.5, 1.4, 0.2]]
sample2 = [[6.2, 2.9, 4.3, 1.3]]
sample3 = [[7.3, 2.9, 6.3, 1.8]]

In [49]:
predictions=(clas.predict(sample1),clas.predict(sample2),clas.predict(sample3))
predictions

(array([0]), array([1]), array([2]))

In [50]:
for i, sample in enumerate([sample1, sample2, sample3]):
    print(f"Sample {i+1}: {sample} --> Predicted class: {iris.target_names[predictions[i][0]]}")

Sample 1: [[5.1, 3.5, 1.4, 0.2]] --> Predicted class: setosa
Sample 2: [[6.2, 2.9, 4.3, 1.3]] --> Predicted class: versicolor
Sample 3: [[7.3, 2.9, 6.3, 1.8]] --> Predicted class: virginica


In [56]:
sample4=[[5.4, 3.9, 1.3, 0.4]]
sample5=[[5. , 2. , 3.5, 1. ]]
sample6=[[6.5, 3. , 5.2, 2. ]]

In [57]:
clas.predict(sample4)

array([0])

In [58]:
clas.predict(sample5)

array([1])

In [59]:
clas.predict(sample6)

array([2])

In [62]:
sample=[[4.0,3.6,2.3,0.5]]
clas.predict(sample)

array([0])