In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

C:\Users\Shruti Mishra\AppData\Local\Temp\ipykernel_17460\494583118.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
from sklearn.datasets import load_iris
iris=load_iris()

In [4]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2)

In [15]:
linear=LogisticRegression()
linear.fit(X_train,y_train)
linear.score(X_test,y_test)

C:\Users\Shruti Mishra\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [16]:
svm=SVC()
svm.fit(X_train,y_train)


SVC()

In [17]:
svm.score(X_test,y_test)

0.9

In [18]:
Decision=DecisionTreeClassifier()
Decision.fit(X_train,y_train)
Decision.score(X_test,y_test)

0.8666666666666667

In [19]:
r=RandomForestClassifier()
r.fit(X_train,y_train)
r.score(X_test,y_test)

0.9

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
score1=cross_val_score(LogisticRegression(),iris.data,iris.target)
score1

C:\Users\Shruti Mishra\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [22]:
np.average(score1)

0.9733333333333334

In [23]:
score2=cross_val_score(SVC(),iris.data,iris.target)
score2

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [24]:
np.average(score2)

0.9666666666666666

In [26]:
score3=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
score3

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [27]:
np.average(score3)

0.9533333333333334

In [28]:
score4=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
score4

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [29]:
np.average(score4)

0.9666666666666668

In [37]:
score5=cross_val_score(RandomForestClassifier(n_estimators=30),iris.data,iris.target)
score5

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [38]:
np.average(score5)

0.9533333333333334